### PR TITLE
React 18 support useId

### PR DESCRIPTION
**Pull request by MarcGuiselin**
Fixes https://github.com/FormidableLabs/react-ssr-prepass/issues/74

### CODE REVIEW

**Comment by kitten** [comment]
Hiya :wave:

It makes complete sense to add support for this; however, I was under the impression that `useOpaqueIdentifier` _is the same_, meaning, that in later versions this was simply renamed, and the logic must remain the same.
You're currently bypassing the actual hooks logic in your implementation, meaning, you won't get a stable identifier, so I assume that this doesn't quite match what the hook is doing.

Furthermore, now that this actually seems in use we likely have to alias this to `unstable_useOpaqueIdentifier` and `unstable_useId` too.

What currently also concerns me is that I'm unclear on what this does and whether we need to take this part of the implementation into account as well: https://github.com/acdlite/react/blob/371302f0144079a7b9f04c3c485ee19cf82b936f/packages/react-reconciler/src/ReactFiberTreeContext.new.js

**Comment by MarcGuiselin** [comment]
Hello! Pleasure to meet you :)

We definitely need to alias those if we want to support pre-releases.

The logic of `useOpaqueIdentifier` was definitely changed, and these changes are outlined in https://github.com/reactwg/react-18/discussions/111 Namely, among other changes:

> ... we're changing the type to be a regular, non-opaque string.

The value returned by `useId` is now a hash representing the component's position in the render tree, plus a number 

## Why I don't think this library needs a "correct" implementation of `useId`

This is my opinion, and I'm fairly new to react so I'm not so sure about this, but hear me out.

The role of this library is to find all thrown promises and wait for them to resolve, not to render the dom completely correct.

I think that per this library's use case, a call to `useId` only needs to return a unique id, nothing more. These ids will likely never be used by the server. They're intended to be used by the client for unique items in forms, matching labels and inputs together, etc.

For example, I don't think any developer would send an id generated by `useId` to a server and expect a unique server response. It just doesn't seem likely for any developers to use `useId` this way, and would be a bad idea IMO

Most developers are just going to use `useId` in very simple contexts and be surprised when SSR throws a `TypeError: dispatcher.useId is not a function`.

## `useId` behaves weird anyway and it's api might still change

In https://github.com/facebook/react/pull/22644 it is described as being a hook.

However, it doesn't completely behave like a hook, otherwise you wouldn't be able to do this. (Code would throw an error if was using `useState` for example)

This is code I wrote myself as an example, and I'm probably not using the hook as intended. But it works.

```js
import { useId } from 'react'

function TestComponent() {
  return <div id={useId()}>I have a unique id that doesn't change across re-renders</div>
}
```

I don't really think this matters for this library. We can just let users use `useId()` the way they want to (even if it's invalid or not) and just return a random, unique string as would be expected. That was my reasoning for implementing it the way I did.

What do you think?

**Comment by kitten** [comment]
I think, it's true that it's not quite like some other hooks. The difference though isainly that it skips some safety checks. It's still supposed to be used like other hooks. That means, while it doesn't protect itself like other hooks, it still maintains internal state and hence problems start to occur when it's called out of order. So, for all intents and purposes we can still treat it like a hook.

Meaning, actually for this library, all we have to do is ensure that it keeps it's memoised states for repeated renders.

I think it's true that the logic doesn't have to match 100% for an initial implementation. So we can likely just ship it as an alias of the old implementation for now 
However, it may matter if it generates different IDs. Internally, a library that deals with SSR state that it rehydrates later, may be relying on this ID remaining stable — not only internally in prepass, but also potentially in a subsequent render.

But yea, for now, we can likely add the aliases and keep it the same as the old `useOpaqueIdentifier` logic that was already in place for now

**Comment by MarcGuiselin** [comment]
I agree. I was incorrect; aliasing useOpaqueIdentifier is definitely the way to go and keeping the same ids across re-renders is definitely important, I could see how not doing that might cause issues.

**Comment by MarcGuiselin** [comment]
Closed in favor of https://github.com/FormidableLabs/react-ssr-prepass/pull/76

**Pull request closed without merging**
